In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn as sb
from sklearn.model_selection import train_test_split
from datetime import datetime
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from scipy import stats

In [2]:
data_load = pd.read_csv("OASIS.csv")
data_weather = pd.read_csv("2021weather.csv")

data_weather = data_weather.drop(columns=['STATION','REPORT_TYPE','REM','HourlyPresentWeatherType','HourlySkyConditions'])
data_weather = data_weather.fillna(0)
data_weather = data_weather.replace('VRB', 0)
data_weather = data_weather.replace('T', 0)
data_weather = data_weather.replace('*', 0)

In [3]:
data_load = data_load.drop(columns=['Zone Name','Zone PTID'])
data_load['RTD End Time Stamp'] = data_load['RTD End Time Stamp'].apply(lambda x:datetime.strptime(x , "%Y/%m/%d %H:%M:%S").strftime("%Y/%m/%d %H")) 
data_load['RTD End Time Stamp'] = pd.to_datetime(data_load['RTD End Time Stamp'], format='%Y/%m/%d %H')

In [4]:
data_load = data_load.groupby(pd.Grouper(key='RTD End Time Stamp',freq='H')).mean()

In [5]:
data_load

                     RTD Actual Load
RTD End Time Stamp
2021-01-01 00:00:00      4800.340962
2021-01-01 01:00:00      4631.978808
2021-01-01 02:00:00      4486.644667
2021-01-01 03:00:00      4372.209042
2021-01-01 04:00:00      4336.574433
...                              ...
2021-04-30 13:00:00      5356.359558
2021-04-30 14:00:00      5349.090400
2021-04-30 15:00:00      5288.151017
2021-04-30 16:00:00      5328.147367
2021-04-30 17:00:00      5335.150438

[2874 rows x 1 columns]

In [6]:
data_weather['DATE'] = data_weather['DATE'].apply(lambda x:datetime.strptime(x , "%Y-%m-%dT%H:%M:%S").strftime("%Y/%m/%d %H")) 
data_weather['DATE'] = pd.to_datetime(data_weather['DATE'], format='%Y/%m/%d %H:%M:%S')

In [7]:
data_weather

,DATE,SOURCE,BackupDirection,BackupDistance,BackupDistanceUnit,BackupElements,BackupEquipment,BackupName,HourlyAltimeterSetting,HourlyDewPointTemperature,...,HourlyPressureTendency,HourlyRelativeHumidity,HourlySeaLevelPressure,HourlyStationPressure,HourlyVisibility,HourlyWetBulbTemperature,HourlyWindDirection,HourlyWindSpeed,REPORT_TYPE.1,SOURCE.1
0,2021-01-01 00:00:00,7,ESE,0.5,mi,SNOW,SNOWBOARD,CENTRAL PARK ZOO,30.44,23,...,1.0,59,30.42,30.27,10.0,31,0,0.0,FM-15,7
1,2021-01-01 01:00:00,7,ESE,0.5,mi,SNOW,SNOWBOARD,CENTRAL PARK ZOO,30.47,23,...,0.0,61,30.44,30.30,10.0,31,0,5.0,FM-15,7
2,2021-01-01 02:00:00,7,ESE,0.5,mi,SNOW,SNOWBOARD,CENTRAL PARK ZOO,30.48,23,...,0.0,61,30.45,30.31,10.0,31,20,5.0,FM-15,7
3,2021-01-01 03:00:00,7,ESE,0.5,mi,SNOW,SNOWBOARD,CENTRAL PARK ZOO,30.48,22,...,1.0,59,30.46,30.31,10.0,30,40,7.0,FM-15,7
4,2021-01-01 04:00:00,7,ESE,0.5,mi,SNOW,SNOWBOARD,CENTRAL PARK ZOO,30.49,23,...,0.0,64,30.47,30.32,10.0,30,20,5.0,FM-15,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3785,2021-04-28 23:00:00,6,ESE,0.5,mi,SNOW,SNOWBOARD,CENTRAL PARK ZOO,0.00,0,...,0.0,0,0.00,0.00,0.0,0,0,0.0,SOD,6
3786,2021-04-29 00:00:00,6,ESE,0.5,mi,SNOW,SNOWBOARD,CENTRAL PARK ZOO,29.83,56,...,6.0,78,29.80,29.66,10.0,59,0,0.0,FM-15,6
3787,2021-04-29 01:00:00,6,ESE,0.5,mi,SNOW,SNOWBOARD,CENTRAL PARK ZOO,29.83,55,...,0.0,81,29.80,29.66,9.0,58,0,0.0,FM-15,6
3788,2021-04-29 02:00:00,6,ESE,0.5,mi,SNOW,SNOWBOARD,CENTRAL PARK ZOO,29.82,53,...,0.0,78,29.79,29.65,10.0,56,0,0.0,FM-15,6
3789,2021-04-29 03:00:00,6,ESE,0.5,mi,SNOW,SNOWBOARD,CENTRAL PARK ZOO,29.80,53,...,8.0,78,29.78,29.63,10.0,56,0,0.0,FM-15,6

In [8]:
data_load

                     RTD Actual Load
RTD End Time Stamp
2021-01-01 00:00:00      4800.340962
2021-01-01 01:00:00      4631.978808
2021-01-01 02:00:00      4486.644667
2021-01-01 03:00:00      4372.209042
2021-01-01 04:00:00      4336.574433
...                              ...
2021-04-30 13:00:00      5356.359558
2021-04-30 14:00:00      5349.090400
2021-04-30 15:00:00      5288.151017
2021-04-30 16:00:00      5328.147367
2021-04-30 17:00:00      5335.150438

[2874 rows x 1 columns]

In [9]:
merge = pd.merge(data_load, data_weather, how='inner', left_on='RTD End Time Stamp', right_on='DATE')

In [10]:
labelencoder = LabelEncoder()
merge['BackupDirection'] = labelencoder.fit_transform(merge['BackupDirection'])
merge['BackupDistanceUnit'] = labelencoder.fit_transform(merge['BackupDistanceUnit'])
merge['BackupElements'] = labelencoder.fit_transform(merge['BackupElements'])
merge['BackupEquipment'] = labelencoder.fit_transform(merge['BackupEquipment'])
merge['BackupName'] = labelencoder.fit_transform(merge['BackupName'])
merge['REPORT_TYPE.1'] = labelencoder.fit_transform(merge['REPORT_TYPE.1'])

In [11]:
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

In [12]:
merge = merge.drop(columns=['DATE'])

In [13]:
clean_dataset(merge)

,RTD Actual Load,SOURCE,BackupDirection,BackupDistance,BackupDistanceUnit,BackupElements,BackupEquipment,BackupName,HourlyAltimeterSetting,HourlyDewPointTemperature,...,HourlyPressureTendency,HourlyRelativeHumidity,HourlySeaLevelPressure,HourlyStationPressure,HourlyVisibility,HourlyWetBulbTemperature,HourlyWindDirection,HourlyWindSpeed,REPORT_TYPE.1,SOURCE.1
0,4800.340962,7.0,0.0,0.5,0.0,0.0,0.0,0.0,30.44,23.0,...,1.0,59.0,30.42,30.27,10.0,31.0,0.0,0.0,0.0,7.0
1,4631.978808,7.0,0.0,0.5,0.0,0.0,0.0,0.0,30.47,23.0,...,0.0,61.0,30.44,30.30,10.0,31.0,0.0,5.0,0.0,7.0
2,4486.644667,7.0,0.0,0.5,0.0,0.0,0.0,0.0,30.48,23.0,...,0.0,61.0,30.45,30.31,10.0,31.0,20.0,5.0,0.0,7.0
3,4372.209042,7.0,0.0,0.5,0.0,0.0,0.0,0.0,30.48,22.0,...,1.0,59.0,30.46,30.31,10.0,30.0,40.0,7.0,0.0,7.0
4,4336.574433,7.0,0.0,0.5,0.0,0.0,0.0,0.0,30.49,23.0,...,0.0,64.0,30.47,30.32,10.0,30.0,20.0,5.0,0.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3785,4538.117208,6.0,0.0,0.5,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,2.0,6.0
3786,4251.927283,6.0,0.0,0.5,0.0,0.0,0.0,0.0,29.83,56.0,...,6.0,78.0,29.80,29.66,10.0,59.0,0.0,0.0,0.0,6.0
3787,4053.131958,6.0,0.0,0.5,0.0,0.0,0.0,0.0,29.83,55.0,...,0.0,81.0,29.80,29.66,9.0,58.0,0.0,0.0,0.0,6.0
3788,3898.938025,6.0,0.0,0.5,0.0,0.0,0.0,0.0,29.82,53.0,...,0.0,78.0,29.79,29.65,10.0,56.0,0.0,0.0,0.0,6.0
3789,3827.728292,6.0,0.0,0.5,0.0,0.0,0.0,0.0,29.80,53.0,...,8.0,78.0,29.78,29.63,10.0,56.0,0.0,0.0,0.0,6.0

Linear Regression

In [14]:
X_train = np.array(merge.drop(columns=['RTD Actual Load']))
y = np.array(merge['RTD Actual Load'])

X_train, X_val, y_train, y_val = train_test_split(X_train, y, test_size=0.2, random_state=42)

In [17]:
reg = LinearRegression().fit(X_train, y_train)
reg.score(X_train, y_train)

0.22421076901077264

lightGBM

In [19]:
import lightgbm as lgb
from lightgbm import LGBMRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
lgb_regressor=lgb.LGBMRegressor(boosting_type='gbdt', objective='regression', num_leaves=500, 
                                learning_rate=0.002, n_estimators=4500, max_bin=500, bagging_fraction=0.8,
                                bagging_freq=5, bagging_seed=9, feature_fraction=0.7, feature_fraction_seed=9, 
                                min_data_in_leaf=6, min_sum_hessian_in_leaf = 10, reg_lambda=0.1, n_jobs=-1)
lgb_regressor.fit(X_train,y_train)
y_head=lgb_regressor.predict(X_val)
print('-'*10+'LGBM'+'-'*10)
print('R square Accuracy: ',r2_score(y_val,y_head))
print('Mean Absolute Error Accuracy: ',mean_absolute_error(y_val,y_head))
print('Mean Squared Error Accuracy: ',mean_squared_error(y_val,y_head))

[LightGBM] [Warning] min_sum_hessian_in_leaf is set=10, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=10
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] feature_fraction is set=0.7, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
----------LGBM----------
R square Accuracy:  0.6622065335387224
Mean Absolute Error Accuracy:  307.5606226163107
Mean Squared Error Accuracy:  164912.0181811264

In [20]:
y_val = y_val.tolist()
y_head = y_head.tolist()